version: "3.8"
services:
  api-serasa-challenge:
    container_name: api-serasa-challenge
    build: ./
    restart: always
    ports:
      - 3000:3000
    env_file:
      - ./.env
    environment:
      APISERASA: api-serasa-challenge
      DATABASE_USER: "postgres"
      DATABASE_PASSWORD: "teste_root"
      DATABASE_NAME: "serasa-challenge"
      DATABASE_PORT: 5432
      DATABASE_HOST: postgres
    depends_on:
      - postgres

  postgres:
    image: 'bitnami/postgresql:latest'
    container_name: db-postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: teste_root
      POSTGRES_USER: postgres
      POSTGRES_DB: serasa-challenge
    ports:
      - 5432:5432
    volumes:
      - db-postgres:/bitnami/postgres

  # pgadmin:
  #   image: dpage/pgadmin4:latest
  #   container_name: pgadmin
  #   restart: always
  #   depends_on:
  #     - postgres
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: user@localhost.com
  #     PGADMIN_DEFAULT_PASSWORD: password
  #   ports:
  #     - 8080:80
  #   volumes:
  #     - ./data/pgadmin:/var/lib/pgadmin

volumes:
  db-postgres:

networks:
  default:
    name: local-network
    external: true